// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJpxHVnVS3DIpvgmgG22F6Kvu3HLCU-n8',
    appId: '1:585036964201:web:609dd9ebee25d4cc04ddf8',
    messagingSenderId: '585036964201',
    projectId: 'trashee-collecter',
    authDomain: 'trashee-collecter.firebaseapp.com',
    storageBucket: 'trashee-collecter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKAI5_VvE73iUDd6g4gqq7Nrvc3QJvT1I',
    appId: '1:585036964201:android:04653a294a954fc704ddf8',
    messagingSenderId: '585036964201',
    projectId: 'trashee-collecter',
    storageBucket: 'trashee-collecter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5IhFvJPlAxRGNhnFYvszdKndZldwqs2w',
    appId: '1:585036964201:ios:b0dcc2bd0ae1646304ddf8',
    messagingSenderId: '585036964201',
    projectId: 'trashee-collecter',
    storageBucket: 'trashee-collecter.firebasestorage.app',
    iosBundleId: 'com.example.trasheeCollecter',
  );
}
